### ISSUE TITLE
HTTP方法修改后怎么自动继承原有的url

### ISSUE THREAD

**Issue by askofcc** [lulianqi/FreeHttp#1]
![Snipaste_2019-07-29_16-48-30](https://user-images.githubusercontent.com/44773069/62034528-c1b3e280-b220-11e9-8a77-2360cc486169.png)

**Comment by lulianqi** [comment]
如果您只是希望在请求替换中使用请求原有url，可以使用参数化功能完成该设置。
以https://www.fiddler2.com/UpdateCheck.aspx?isBeta=False为例。
1：在请求替换规则中添加参数拾取
![image](https://user-images.githubusercontent.com/23115455/62071843-f8651980-b26f-11e9-943a-6b7ce08a2176.png)
如上图添加一个my_url参数（参数化系统详见https://www.cnblogs.com/lulianqi/p/10428551.html#_label8）
2：在请求替换中使用刚刚的参数化数据
![image](https://user-images.githubusercontent.com/23115455/62072350-0a938780-b271-11e9-931a-e03ada48ce5d.png)
如上图使用参数化数据（可以使用RAW模式辅助添加参数化数据，详细操作可以查看上面链接处操作说明）

保存生效后可以看到效果
![image](https://user-images.githubusercontent.com/23115455/62072746-d66c9680-b271-11e9-8a6a-e5f8b0ea0797.png)
![image](https://user-images.githubusercontent.com/23115455/62072782-ea17fd00-b271-11e9-8d8e-9765b3ebe992.png)

可以看到GET已经变成POST并且url也是如预期
通过日志可以看到参数拾取过程（简单说明下，freehttp在收到请求后会先在原始请求中拾取参数，然后进行修改或替换，所以在同一个请求中拾取的参数就可以直接使用）
