### ISSUE TITLE
有办法通过该插件解决A域名重定向到B域名后的，Cookie跨域的问题么？

### ISSUE THREAD

**Issue by hhs66317** [lulianqi/FreeHttp#15]
现在需要对线上的接口（A域名）通过Freehttp重定向到测试环境（域名B），该业务需要用到服务端下发的Cookie，涉及到跨域问题，有办法添加额外规则来解决该问题么？

**Comment by lulianqi** [comment]
@hhs66317 
一般情况下，如果您重定向到测试环境，那测试服务可能不会承认线上服务的的cookies。
不过如果您的业务在调试或测试过程中确实有这样的需求，freehttp可以做到，而且为cookie操作提供了快速设置功能。
**下面我将以将jd.com 的cookies 设置到cn.bing.com 为例向您演示目标功能**
![image](https://user-images.githubusercontent.com/23115455/177195770-28d15e2a-e758-4716-a757-dda81473aaae.png)
如上图在左侧列表中选择jd.com的目标session，然后点击[Quick Rule]>[copy session cookies] ,Free Http 会自动为您填充响应篡改规则，将jd.com的cookie注入到新的域名下 
![image](https://user-images.githubusercontent.com/23115455/177196218-613dca1c-1913-4d0c-85f8-50589928e51e.png)
cookie注入实际上通过response的set cookies 响应头实现的，如果有需要对指定cookie有跟细节的控制，如子域名，有效期等可以直接编辑自动生成的规则
然后就是重定向，这个设置比较简单，直接使用响应篡改模板即可完成，我们这里假设加入jd手机专区的时候进行重定向
![image](https://user-images.githubusercontent.com/23115455/177196755-a00499c9-2c68-4112-9124-2a7cdee6ea94.png)
如上图选择相应模板做简单修改即可。

**下面是效果**
![image](https://user-images.githubusercontent.com/23115455/177197094-486b6db8-e5f4-4e89-adbc-44ad65dd2878.png)
![image](https://user-images.githubusercontent.com/23115455/177197171-43edc134-9cd1-4232-9389-fcab233a7480.png)

可以看到我们再次加入jd手机的时候，就会被直接重定向到bing，并且新的域下被写入了许多jd的cookies

**直接使用上文中的例子**
如果您当前使用的是FreeHttp 2.3及以上版本，您可以直接使用上文中的例子
以上相关规则我已经分享到云端 ，获取token为 【27fd3332873d4f659e29136a9d5c211d】您可以直接使用该token同步示例到您的本地规则列表
如何使用分享功能 详见 https://www.cnblogs.com/lulianqi/p/15921187.html#_label1_1

**Comment by hhs66317** [comment]
@lulianqi 
我认真看了你提供的方案，看起来不能解决我的问题，之前纯文字的表述可能让你有所误解，我也已贴图的方式来尝试重新表述一下：

我当前的规则如下：

![image](https://user-images.githubusercontent.com/3916247/177924032-034f7ef4-0b52-4729-b26b-81563b0f00f3.png)

当我访问 www.fiddler2.com 时，我希望访问到测试环境 www.st1-fiddler.com ，这个测试环境 www.st1-fiddler.com 会下发 cookie ，当继续访问 www.fiddler2.com 的其他页面时，没办法把之前下发的 cookie 在请求时带到服务端，导致无法认证。

我希望可以有办法将下发的 cookie，自动处理一下，让测试环境返回的 cookie 适合 正式环境页面的使用。

**Comment by lulianqi** [comment]
> 



> @lulianqi 我认真看了你提供的方案，看起来不能解决我的问题，之前纯文字的表述可能让你有所误解，我也已贴图的方式来尝试重新表述一下：
> 
> 我当前的规则如下：
> 
> ![image](https://user-images.githubusercontent.com/3916247/177924032-034f7ef4-0b52-4729-b26b-81563b0f00f3.png)
> 
> 当我访问 [www.fiddler2.com](http://www.fiddler2.com) 时，我希望访问到测试环境 [www.st1-fiddler.com](http://www.st1-fiddler.com) ，这个测试环境 [www.st1-fiddler.com](http://www.st1-fiddler.com) 会下发 cookie ，当继续访问 [www.fiddler2.com](http://www.fiddler2.com) 的其他页面时，没办法把之前下发的 cookie 在请求时带到服务端，导致无法认证。
> 
> 我希望可以有办法将下发的 cookie，自动处理一下，让测试环境返回的 cookie 适合 正式环境页面的使用。

如果您直接修改了host，请求响应将来自测试服务器，cookies也是测试服务器的cookies，不过这个时候浏览器依然以为自己是线上的域名，所以cookies是写到线上域名的，后面如果您继续访问的是线上域名那么请求就会带上测试的cookie（因为服务器不同cookies不一定会被线上服务验证成功），如果后续访问的是测试域名则不会带上刚刚的cookies。
在测试的时候要留意cookies的生命周期是不是只在当前会话生效。freehttp可以任意修改http报文，不过cookie的管理是浏览器在做。要结合浏览器对cookie的管理方式，通过freehttp是可以完成对cookies的高度控制的。
