### ISSUE TITLE
FreeHttp的Rule配置保存不是实时么？多次遇到将规则移动到其他分组后，重启fiddler后规则又恢复到默认分组的问题

### ISSUE THREAD

**Issue by hhs66317** [lulianqi/FreeHttp#18]
如题：

当把几条 rule 从 default 分组移动到自定义分组后，可以正常使用，但是重启fiddler后，多次出现之前移动的 rule 又从自定义分组跑到 default 分组的情况。

是因为配置的保存不是实时么？还是关闭fiddler时，把内存中的旧数据又写到文件中了？

另外还有一个情况，当移动规则到其他分组后，本来其他分组中的A规则是选中状态，变成了B是选中状态，可能在移动规则后，选中状态没有处理妥当吧

**Comment by lulianqi** [comment]
> 如题：
> 
> 当把几条 rule 从 default 分组移动到自定义分组后，可以正常使用，但是重启fiddler后，多次出现之前移动的 rule 又从自定义分组跑到 default 分组的情况。
> 
> 是因为配置的保存不是实时么？还是关闭fiddler时，把内存中的旧数据又写到文件中了？
> 
> 另外还有一个情况，当移动规则到其他分组后，本来其他分组中的A规则是选中状态，变成了B是选中状态，可能在移动规则后，选中状态没有处理妥当吧

保存会实时更新到应用内存，关闭fiddler的时候会更新配置文件（本地存储文件）。如果非正常退出fiddler可能会导致FreeHttp无法正确回写（强制结束进程，强制退出）
