### ISSUE TITLE
希望可以在创建规则时增加备注说明，可以在规则列表鼠标悬停时显示

### ISSUE THREAD

**Issue by OwnerCM** [lulianqi/FreeHttp#20]
日常使用的规则越来越多，但规则列表无法快速区分具体规则，需要一条条点开确认，希望可以在创建规则时增加备注说明，可以在规则列表鼠标悬停时显示

**Comment by lulianqi** [comment]
> 日常使用的规则越来越多，但规则列表无法快速区分具体规则，需要一条条点开确认，希望可以在创建规则时增加备注说明，可以在规则列表鼠标悬停时显示

已有功能特性 见 ：https://www.cnblogs.com/lulianqi/p/10428551.html#1.3
高级过滤条件中的Rule Alias 部分用于设置该规则的别名 （设置过别名后该别名会显示在后面 『Tamper Rule』篡改规则列表区）

您可以先看下这个是否已经满足了需要！

**Comment by OwnerCM** [comment]
> > 日常使用的规则越来越多，但规则列表无法快速区分具体规则，需要一条条点开确认，希望可以在创建规则时增加备注说明，可以在规则列表鼠标悬停时显示
> 
> 已有功能特性 见 ：https://www.cnblogs.com/lulianqi/p/10428551.html#1.3 高级过滤条件中的Rule Alias 部分用于设置该规则的别名 （设置过别名后该别名会显示在后面 『Tamper Rule』篡改规则列表区）
> 
> 您可以先看下这个是否已经满足了需要！

可以满足要求，这个工具真的很强大，而且考虑的非常全面，谢谢大佬！
不知道这个工具能不能兼容anywhere？

**Comment by lulianqi** [comment]
> 
不客气，也十分感谢您的建议!
Fiddler Everywhere 暂时没有开放扩展支持，暂未兼容。不过FreeHttp计划将会有独立跨平台版本，届时可以在脱离Fiddler的环境下继续使用。

**Comment by lulianqi** [comment]
> 
不客气，也十分感谢您的建议!
Fiddler Everywhere 暂时没有开放扩展支持，暂未兼容。不过FreeHttp计划将会有独立跨平台版本，届时可以在脱离Fiddler的环境下继续使用。
