### ISSUE TITLE
请问大佬，FreeHttp的request是否支持修改post文件

### ISSUE THREAD

**Issue by OwnerCM** [lulianqi/FreeHttp#22]
Composer可以支持body的文件上传，请问FreeHttp request是否支持post文件替换，如何操作？
尝试使用add file，但是post直接把文件路径上传了，并没有上传文件。
如下：
---------------------------12345654321
Content-Disposition: form-data; name="img"; filename=""
Content-Type: application/octet-stream

<<replace file path>>E:\IMG_20161002_105106.jpg
---------------------------12345654321--

**Comment by lulianqi** [comment]
> Composer可以支持body的文件上传，请问FreeHttp request是否支持post文件替换，如何操作？ 尝试使用add file，但是post直接把文件路径上传了，并没有上传文件。 如下： ---------------------------12345654321 Content-Disposition: form-data; name="img"; filename="" Content-Type: application/octet-stream
> 
> <>E:\IMG_20161002_105106.jpg ---------------------------12345654321--

https://www.cnblogs.com/lulianqi/p/10428551.html#%C2%A02.2.3-%E3%80%8Erequest-body%E3%80%8F%E7%BC%96%E8%BE%91%E6%9B%BF%E6%8D%A2%E8%AF%B7%E6%B1%82%E4%BD%93
request 的替换可以在请求实体里直接使用本地文件 （如文档中的介绍），对于request 的编辑不能直接支持使用本地文件，不过您可以尝试使用hex模式直接修改文件 https://www.cnblogs.com/lulianqi/p/11051753.html#_label1_0 （如文档中的介绍）

**Comment by OwnerCM** [comment]
> request 的替换可以在请求实体

我通过这种方式添加了文件，但是最终请求的结果是直接把文件url上传了，而并没有把文件解析上传
https://img2018.cnblogs.com/blog/209007/201902/209007-20190226111219912-108734517.png

**Comment by lulianqi** [comment]
> 

![image](https://github.com/lulianqi/FreeHttp/assets/23115455/261606ab-5ddc-4326-80dc-27f761454e4f)
关注文档中的描述，请确认是否在请求实体中间的位置添加了文件，本地文件只能被添加到开头才能被识别，如果要个性化实体内容，可以直接修改文件内容。  您也可以将您无法正常工作的规则分享出来，以方便问题的确认
https://www.cnblogs.com/lulianqi/p/15921187.html#_label1_1 （如何分享规则，如文档描述）
