### ISSUE TITLE
怎么修改请求的json数据？

### ISSUE THREAD

**Issue by jklop000** [lulianqi/FreeHttp#24]
如果content-type是application/json，在Fiddler的TextView面板里是json的数据是{"id":1,"name":"张三"}，那怎么在freehttp中修改这个请求json数据中的"name"为"李四"啊？

**Comment by lulianqi** [comment]
无论是请求还是响应，application/json的本质仍然是文本，按文本修改处理即可
https://www.cnblogs.com/lulianqi/p/10428551.html#2.1.4%EF%BC%9A%E8%AF%B7%E6%B1%82%E4%BD%93body%E4%BF%AE%E6%94%B9%E3%80%8Ebody-modific%E3%80%8F

直接创建篡改规则将"name":"张三"改为"name":"李四"即可
如果有更复杂的数据结构，通过文本难以匹配，可以使用正则表达式模式处理 （上面的链接中也有提示）

**Comment by lulianqi** [comment]
> 如果content-type是application/json，在Fiddler的TextView面板里是json的数据是{"id":1,"name":"张三"}，那怎么在freehttp中修改这个请求json数据中的"name"为"李四"啊？

无论是请求还是响应，application/json的本质仍然是文本，按文本修改处理即可
https://www.cnblogs.com/lulianqi/p/10428551.html#2.1.4%EF%BC%9A%E8%AF%B7%E6%B1%82%E4%BD%93body%E4%BF%AE%E6%94%B9%E3%80%8Ebody-modific%E3%80%8F

直接创建篡改规则将"name":"张三"改为"name":"李四"即可
如果有更复杂的数据结构，通过文本难以匹配，可以使用正则表达式模式处理 （上面的链接中也有提示）
