### ISSUE TITLE
Resonse Replace 疑似bug

### ISSUE THREAD

**Issue by irvineyang** [lulianqi/FreeHttp#4]
作者你好！

我在使用你的free http，在Response Replace中，如果启用高级筛选，不管是使用“Head Filter”或"HTTP Body Filter"，一旦填入都无法成功匹配。而不使用高级筛选的话，则无问题。不知道是我使用上的问题，还是插件存在bug。

另外我自己想到的是，Responese Modific中，高级筛选是对响应中的信息进行筛选的，而Response Replace没有响应，如果高级筛选还是对响应中的信息进行筛选的话，则启动高级筛选的话肯定匹配不了任何对话。

那么，是否能对Resonse Replace中的高级筛选功能所筛选的信息是请求中的信息呢？根据请求的信息（head信息和body信息），决定是否对响应进行替换？因为我也正好需要根据请求信息去替换整个响应。

望回复，谢谢！

**Comment by lulianqi** [comment]
您好！感谢您的反馈。
设计上Http Filter 是仅针对Request进行筛选
实现上的错误已经修复，您可以更新新的版本进行测试。
当前的设计
   HTTP >  Filter 中的 url，head，body都针对Request进行过滤
   Websocket  > Filter  中 url 针对 Websocket  握手的url进行过滤，payload 区分是Request或Response进行过滤

**Comment by irvineyang** [comment]
您好，感谢您深夜继续修复bug，请问新版本的DLL在哪里下载呢？我找了一轮还没找到下载链接，谢谢！

**Comment by irvineyang** [comment]
在你的博客里面看到更新后的下载链接了，谢谢！
